### ISSUE TITLE
Cannot load addon

### ISSUE THREAD

**Issue by tayadev** [MagnumVD/RotoForge-AI#9]
Addon errors out on load with the following error:
```
Exception in module register(): C:\Users\taya\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RotoForge-AI\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\taya\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RotoForge-AI\__init__.py", line 114, in register
    from .functions import setup_ui
  File "C:\Users\taya\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RotoForge-AI\functions\setup_ui.py", line 6, in <module>
    from . import generate_masks
  File "C:\Users\taya\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RotoForge-AI\functions\generate_masks.py", line 10, in <module>
    from .overlay import rotoforge_overlay_shader
  File "C:\Users\taya\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\RotoForge-AI\functions\overlay.py", line 38, in <module>
    batch = gpu_extras.batch.batch_for_shader(
            ^^^^^^^^^^^^^^^^
AttributeError: module 'gpu_extras' has no attribute 'batch'
```

Changing the line `import gpu_extras` in overlay.py to `import gpu_extras.batch` fixes this error

System Info:
- Addon Version: 1.0.0
- Blender 4.1.1
- Windows 11

**Comment by MagnumVD** [comment]
Fixed by https://github.com/MagnumVD/RotoForge-AI/pull/10
